### ISSUE TITLE
Rebuild for Retsly Secure Sign-On

### ISSUE THREAD

**Issue by switters** [Retsly/retsly-js-auth#29]
- [ ] ~~~Correctly size for Retsly Secure Sign-On~~~
- [ ] Remove backbone
- [x] Accept vendor id
- [ ] ~~~Add drop down for picking vendors~~~

**Comment by slajax** [comment]
I like the new branding. @kregensberg Should we surface "Retsly Secure Sign on" onto the page or collateral somewhere? I like the ring of it.

**Comment by kregensberg** [comment]
Already ahead of you

![image](https://cloud.githubusercontent.com/assets/6578999/8943174/4ead8944-352e-11e5-960c-66ab321de508.png)
